/**
 * 常量类
 */
export default class Constants {
  /**
   * 云音乐API地址
   */
  static readonly ROOT_URL: string = 'http://111.229.38.178:3000'
  /**
   * 一般API地址
   */
  static readonly API_URL: string = 'https://api.chenlvin.cc'
  /**
   * Cookie有效时间(Days)
   */
  static readonly COOKIE_EXPIRY_DAYS: number = 21
  /**
   * 开关组件高度
   */
  static readonly HEIGHT_TOGGLE: number = 30
  /**
   * 选择框高度
   */
  static readonly HEIGHT_SELECT: number = 40
  /**
   * 文字按钮高度
   */
  static readonly HEIGHT_TEXT_BUTTON: number = 40
  /**
   * MenuItem 默认尺寸
   */
  static readonly HEIGHT_MENU_ITEM_DEFAULT: number = 40
  /**
   * 设置项高度
   */
  static readonly HEIGHT_SETTINGS_ITEM: number = 50
  /**
   * 默认圆形icon按钮尺寸
   */
  static readonly SIZE_ICON_BUTTON_COMMON: number = 35
  /**
   * Head Icon按钮尺寸
   */
  static readonly SIZE_ICON_BUTTON_HEAD: number = 30
  /**
   * Bar Icon 按钮尺寸
   */
  static readonly SIZE_ICON_BUTTON_BAR: number = 25
  /**
   * 默认加载图标尺寸
   */
  static readonly SIZE_LOADING_PROGRESS_DEFAULT: number = 50
  /**
   * 卡片加载图标尺寸
   */
  static readonly SIZE_LOADING_PROGRESS_CARD: number = 30
  /**
   * 卡片图片 Image 尺寸
   */
  static readonly SIZE_IMG_CARD: number = 50
  /**
   * 卡片边框弧度
   */
  static readonly RADIUS_CARD: number = 15
  /**
   * 按钮边框弧度
   */
  static readonly RADIUS_BUTTON: number = 15
  /**
   * Image 默认弧度
   */
  static readonly RADIUS_IMG: number = 5
  /**
   * 标题栏字体尺寸
   */
  static readonly FONT_SIZE_TITLE: number = 20
  /**
   * 普通字体尺寸
   */
  static readonly FONT_SIZE_COMMON: number = 15
  /**
   * Bar 字体尺寸
   */
  static readonly FONT_SIZE_BAR: number = 10
  /**
   * 默认边缘避让尺寸
   */
  static readonly PADDING_EDGE_DEFAULT: number = 10
  /**
   * 文字类边缘避让尺寸
   */
  static readonly PADDING_EDGE_TEXT: number = 30
  /**
   * Sheet 顶部默认避让尺寸
   */
  static readonly PADDING_SHEET_TOP_DEFAULT: number = 60
}