/**
 * 常量类
 */
export default class Constants {
  // Base Urls
  static readonly ROOT_URL: string = 'http://111.229.38.178:3000'
  static readonly EAPI_URL: string = 'https://interface.music.163.com/eapi'
  static readonly MUSIC_URL: string = 'https://music.163.com'
  static readonly API_URL: string = 'https://api.chenlvin.cc'

  /**
   * Cookie有效时间(Days)
   */
  static readonly COOKIE_EXPIRY_DAYS = 28
}