export class EmitterConstants {
  /**
   * Emitter
   * 更新歌词
   */
  static readonly EMITTER_LYRIC_UPDATE: string = 'LYRIC_UPDATE'
  /**
   * Emitter
   * 更新搜索内容
   */
  static readonly EMITTER_SEARCH: string = 'SEARCH'
  /**
   * Emitter
   * 刷新播放列表
   */
  static readonly EMITTER_REFRESH_PLAYQUEUE: string = 'REFRESH_PLAYQUEUE'
  /**
   * 从歌单中删除歌曲
   */
  static readonly EMITTER_DELETE_FROM_PLAYLIST: string = 'DELETE_FROM_PLAYLIST'
}